---

- name: keycloak
  link: https://github.com/keycloak/keycloak
  description: |
    Open Source Identity and Access Management For Modern Applications and Services. 
    This repository contains the source code for the Keycloak Server, Java adapters and 
    the JavaScript adapter.
  references:
  - https://www.keycloak.org/

